meta:
  title:
  navigation:
    
seo:
  description:
    default: 
  keywords:
    default: 

development:
  domain: localhost:3000
  
test:
  domain: test.host

production:
  domain: example.com
  google_analytics_account_id: ""

dispatcher:

